### ISSUE TITLE
10-18 Keys Leather Sync Not Working

### ISSUE THREAD

**Issue by Cemehzhurin** [TheLeerName/mania-converter#4]
im trying to convert tutorial to 18 keys. and since leather has 10-18 keys, the converter did not care, and was like: "key count more than 9".

**Comment by TheLeerName** [comment]
I wrote `"Support from 1 key to 9 keys, but you can write your algorithm in folder algorithms for 10 keys and more!"` in GameBanana page, but why do you need so many keys? :D

**Comment by Cemehzhurin** [comment]
im kinda lazy to do the 10 key algorithm ngl

**Comment by TheLeerName** [comment]
> im kinda lazy to do the 10 key algorithm ngl

im too.lol

**Comment by Cemehzhurin** [comment]
y'know what imma close this issue
