### ISSUE TITLE
An chart wont chart to osu!mania

### ISSUE THREAD

**Issue by mastermancha** [TheLeerName/mania-converter#6]
Hello, I'm doing this request if it's an error or something, but I'm just gonna say the issue.
So, I wanted to make a new chart for osu! mania (four-way fracture to be exact, check if there is something with the chart:https://drive.google.com/drive/folders/151reAEKP0jIAmXD07Yx9nrP1DAlpzWIh) and the thing is, that you see I made all things working yknow the mode is to 2, the side is also 2 and all. but I don't know why, but the chart won't go to the correct folder. Like, all other charts works but not this specific one. can you do something about it? or if there's an error on the charting section and anything...
Thank you in advance!

**Comment by TheLeerName** [comment]
your chart has mania 0 lol maybe it problem

**Comment by mastermancha** [comment]
hi again! sorry for the late response, but what mania 0?

**Comment by TheLeerName** [comment]
a month later no response, ok
